version: '3.9'
services:
 postgres:
  image: postgres:latest
  container_name: workoutDB
  restart: always
  environment:
   POSTGRES_USER_FILE: /run/secrets/postgres-u
   POSTGRES_PASSWORD_FILE: /run/secrets/postgres-p
   POSTGRES_DB: WorkoutHelper
  ports:
   - 5432:5432
  volumes:
   - db-volume:/var/lib/postgresql/data
  secrets:
   - postgres-u
   - postgres-p

 api:
  build: .
  container_name: workoutAPI
  ports:
   - 5000:8080
  depends_on:
   - "postgres"
  secrets:
   - postgres-u
   - postgres-p
   - jwt-key

secrets:
 postgres-u:
  file: postgres-u.txt
 postgres-p:
  file: postgres-p.txt
 jwt-key:
  file: jwt-key.txt

volumes:
  db-volume: